/* Generated By:JJTree: Do not edit this line. ASTAddOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddOperation extends SimpleNode {
  public ASTAddOperation(int id) {
    super(id);
  }

  public ASTAddOperation(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=745085bf2f4c8e29c3e2581bf8615843 (do not edit this line) */
