/* Generated By:JJTree: Do not edit this line. ASTCompare_Op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCompare_Op extends SimpleNode {
  public ASTCompare_Op(int id) {
    super(id);
  }

  public ASTCompare_Op(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1bb09a09e22ca90f75edb56ea2d81d53 (do not edit this line) */
