/* Generated By:JJTree: Do not edit this line. ASTFunctionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionList extends SimpleNode {
  public ASTFunctionList(int id) {
    super(id);
  }

  public ASTFunctionList(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73b5d1ba2a74875e58fe8ffa5565f8c1 (do not edit this line) */
