/* Generated By:JJTree: Do not edit this line. ASTFunc_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunc_decl extends SimpleNode {
  public ASTFunc_decl(int id) {
    super(id);
  }

  public ASTFunc_decl(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=da04b9400cdd23630a0c8a37180e5d9d (do not edit this line) */
