/* Generated By:JJTree: Do not edit this line. ASTMath_Op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMath_Op extends SimpleNode {
  public ASTMath_Op(int id) {
    super(id);
  }

  public ASTMath_Op(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e74d886c8496861001e11fd4e4bc6148 (do not edit this line) */
