/* Generated By:JJTree: Do not edit this line. ASTSubOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSubOperation extends SimpleNode {
  public ASTSubOperation(int id) {
    super(id);
  }

  public ASTSubOperation(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71dd2c9a71cbd953c3cba5a0c6a40fa5 (do not edit this line) */
