/* Generated By:JJTree: Do not edit this line. ASTWhileCond.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileCond extends SimpleNode {
  public ASTWhileCond(int id) {
    super(id);
  }

  public ASTWhileCond(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=74eb466e11bf71ad90476ca1463529b7 (do not edit this line) */
