/* Generated By:JavaCC: Do not edit this line. CCALTreeConstants.java Version 5.0 */
public interface CCALTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR_DECL = 2;
  public int JJTCONST_DECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTTYPE = 5;
  public int JJTPARAM = 6;
  public int JJTMAIN = 7;
  public int JJTSTATEMENT = 8;
  public int JJTIF = 9;
  public int JJTWHILE = 10;
  public int JJTASSIGN = 11;
  public int JJTMATH_OP = 12;
  public int JJTFRAGMENT = 13;
  public int JJTID = 14;
  public int JJTNUMBER = 15;
  public int JJTBOOLEAN = 16;
  public int JJTLOGIC_OP = 17;
  public int JJTCOMPARE_OP = 18;
  public int JJTARG = 19;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Var_decl",
    "Const_decl",
    "Function",
    "Type",
    "Param",
    "Main",
    "Statement",
    "If",
    "While",
    "ASSIGN",
    "Math_Op",
    "Fragment",
    "Id",
    "Number",
    "Boolean",
    "Logic_Op",
    "Compare_Op",
    "Arg",
  };
}
/* JavaCC - OriginalChecksum=2d26a996f878f11e2a35ffc40c65f2db (do not edit this line) */
