/* Generated By:JavaCC: Do not edit this line. CCALVisitor.java Version 5.0 */
public interface CCALVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVar_decl node, Object data);
  public Object visit(ASTConst_decl node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTParam node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTIfCond node, Object data);
  public Object visit(ASTWhileCond node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTMath_Op node, Object data);
  public Object visit(ASTAddOperation node, Object data);
  public Object visit(ASTSubOperation node, Object data);
  public Object visit(ASTFragment node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTLogic_Op node, Object data);
  public Object visit(ASTCompare_Op node, Object data);
  public Object visit(ASTArg node, Object data);
}
/* JavaCC - OriginalChecksum=ab14c2d692b18ca8646e07c78340bcb6 (do not edit this line) */
