/* Generated By:JavaCC: Do not edit this line. CCALTreeConstants.java Version 5.0 */
public interface CCALTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR_DECL = 2;
  public int JJTCONST_DECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTTYPE = 5;
  public int JJTPARAM = 6;
  public int JJTMAIN = 7;
  public int JJTSTATEMENT = 8;
  public int JJTIFCOND = 9;
  public int JJTWHILECOND = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTMATH_OP = 12;
  public int JJTADDOPERATION = 13;
  public int JJTSUBOPERATION = 14;
  public int JJTFRAGMENT = 15;
  public int JJTID = 16;
  public int JJTNUMBER = 17;
  public int JJTBOOLEAN = 18;
  public int JJTLOGIC_OP = 19;
  public int JJTCOMPARE_OP = 20;
  public int JJTARG = 21;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Var_decl",
    "Const_decl",
    "Function",
    "Type",
    "Param",
    "Main",
    "Statement",
    "IfCond",
    "WhileCond",
    "Assignment",
    "Math_Op",
    "AddOperation",
    "SubOperation",
    "Fragment",
    "Id",
    "Number",
    "Boolean",
    "Logic_Op",
    "Compare_Op",
    "Arg",
  };
}
/* JavaCC - OriginalChecksum=169656a86cfd388ba4e7f6c87eccb683 (do not edit this line) */
