/* Generated By:JavaCC: Do not edit this line. CCALTreeConstants.java Version 5.0 */
public interface CCALTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR_DECL = 2;
  public int JJTCONST_DECL = 3;
  public int JJTFUNCTIONLIST = 4;
  public int JJTFUNC_DECL = 5;
  public int JJTFUNC_BODY = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMLIST = 8;
  public int JJTMAIN = 9;
  public int JJTIFCOND = 10;
  public int JJTWHILECOND = 11;
  public int JJTASSIGNMENT = 12;
  public int JJTFUNCTIONCALL = 13;
  public int JJTADDOPERATION = 14;
  public int JJTSUBOPERATION = 15;
  public int JJTID = 16;
  public int JJTNUMBER = 17;
  public int JJTBOOLEAN = 18;
  public int JJTLOGIC_OP = 19;
  public int JJTCOMPARE_OP = 20;
  public int JJTARGLIST = 21;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Var_decl",
    "Const_decl",
    "FunctionList",
    "Func_decl",
    "Func_body",
    "Type",
    "ParamList",
    "Main",
    "IfCond",
    "WhileCond",
    "Assignment",
    "FunctionCall",
    "AddOperation",
    "SubOperation",
    "Id",
    "Number",
    "Boolean",
    "Logic_Op",
    "Compare_Op",
    "ArgList",
  };
}
/* JavaCC - OriginalChecksum=6d20af1c557dc8a225a65fc4efa137d0 (do not edit this line) */
