/* Generated By:JJTree: Do not edit this line. ASTFunction_Decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction_Decl extends SimpleNode {
  public ASTFunction_Decl(int id) {
    super(id);
  }

  public ASTFunction_Decl(BasicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=32f998881afb5d0cf16449c0527ba873 (do not edit this line) */
