/* Generated By:JJTree: Do not edit this line. ASTFunction_body.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction_body extends SimpleNode {
  public ASTFunction_body(int id) {
    super(id);
  }

  public ASTFunction_body(BasicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=44496150e7d5d0c6e7a2afced39a88ea (do not edit this line) */
