/* Generated By:JJTree: Do not edit this line. ASTIdent_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdent_list extends SimpleNode {
  public ASTIdent_list(int id) {
    super(id);
  }

  public ASTIdent_list(BasicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c2ee61a71b4c05c778ec80e2d53712d (do not edit this line) */
