/* Generated By:JJTree: Do not edit this line. ASTReal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReal extends SimpleNode {
  private String name;
  public ASTReal(int id) {
    super(id);
  }

  public ASTReal(BasicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Real: " + name;
  }
}
/* JavaCC - OriginalChecksum=ce7e127feb0d83d9d3782e3cd51f4ae8 (do not edit this line) */
