/* Generated By:JavaCC: Do not edit this line. BasicLTreeConstants.java Version 5.0 */
public interface BasicLTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTFUNCTION_DECL = 4;
  public int JJTFUNCTION_BODY = 5;
  public int JJTPARAMS = 6;
  public int JJTTYPE = 7;
  public int JJTMAIN = 8;
  public int JJTASSIGN = 9;
  public int JJTADD = 10;
  public int JJTMULT = 11;
  public int JJTADDOP = 12;
  public int JJTMULTOP = 13;
  public int JJTBOOLOPP = 14;
  public int JJTCONDITION = 15;
  public int JJTIDENT_LIST = 16;
  public int JJTARG_LIST = 17;
  public int JJTID = 18;
  public int JJTNUM = 19;
  public int JJTBOOL = 20;
  public int JJTREAL = 21;
  public int JJTFUNCTIONCALL = 22;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Decl",
    "ConstDecl",
    "Function_Decl",
    "Function_body",
    "Params",
    "Type",
    "Main",
    "Assign",
    "Add",
    "Mult",
    "AddOp",
    "MultOp",
    "BoolOpp",
    "Condition",
    "Ident_list",
    "Arg_list",
    "Id",
    "Num",
    "Bool",
    "Real",
    "FunctionCall",
  };
}
/* JavaCC - OriginalChecksum=5b3646fe14b921834969997274778c28 (do not edit this line) */
